### ISSUE TITLE
EventLevel is no longer available

### ISSUE THREAD

**Issue by Martina-B** [awslabs/amazon-quicksight-embedding-sdk#189]
After update from 2.3.1 to 2.5.0 the property eventLevel is no longer existing in renamed type EmbeddingEvents.

We use it for catching Errors. It is also a recommended way of catching errors from README. So either README was not updated or the eventLevel should still be there...

This code throws `Property 'eventLevel' does not exist on type 'EmbeddingEvents'.`

```
const frameOptions = {
    //...
    onChange: (changeEvent: EmbeddingEvents, metadata: ExperienceFrameMetadata) => {
        if (changeEvent.eventLevel === 'ERROR') {
            console.log(`Do something when embedding experience failed with "${changeEvent.eventName}"`);
            return;
        }
        switch (changeEvent.eventName) {
            case 'FRAME_MOUNTED': {
                console.log("Do something when the experience frame is mounted.");
                break;
            }
            case 'FRAME_LOADED': {
                console.log("Do something when the experience frame is loaded.");
                break;
            }
            case 'FRAME_REMOVED': {
                console.log("Do something when the experience frame is removed.");
                break;
            }
            //...
        }
    },
};
```

**Comment by sonals-amazon** [comment]
This example in our READNE seems to be incorrect. If you change the  `EmbeddingEvents` type to `ChangeMessageEvents` type it should work.

**Comment by Martina-B** [comment]
Thank you! That's the good type.
Closing the issue, but it would be nice to update it in README.
